name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.1.3
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/logger_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.1
  sensors_plus: ^3.0.3
  share_plus: ^7.1.0
